# Generated by Django 4.1.5 on 2023-01-08 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plataform_name', models.CharField(max_length=512)),
                ('plataform_tax', models.DecimalField(decimal_places=2, max_digits=19)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.imovel')),
            ],
        ),
    ]
