# Generated by Django 4.1.5 on 2023-01-08 20:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_anuncio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chekin_at', models.DateField()),
                ('checkout_at', models.DateField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=19)),
                ('comment', models.TextField(blank=True, max_length=2048)),
                ('guest_amount', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_anuncio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.anuncio')),
            ],
        ),
    ]
